version: "3"

services:
  app:
    image: dyaonly/sprboot:template
#    build:
#      context: ./
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
#    links:
#      - mariadb

#  mariadb:
#    image: mariadb
#    expose:
#      - 3306
#    volumes:
#      - ./data/db:/var/lib/mysql:rw
#    environment:
#      - MARIADB_ROOT_PASSWORD=root
#      - MARIADB_DATABASE=springboot